// <auto-generated />
using System;
using KT.Quanta.Service.Daos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KT.Quanta.Service.Migrations
{
    [DbContext(typeof(QuantaDbContext))]
    [Migration("20210330073521_v1.5.374")]
    partial class v15374
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KT.Quanta.Entity.Entities.HandleElevatorDeviceAuxiliaryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("HandleElevatorDeviceId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsFront")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRear")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("HandleElevatorDeviceId")
                        .IsUnique();

                    b.ToTable("HANDLE_ELEVATOR_DEVICE_AUXILIARY");
                });

            modelBuilder.Entity("KT.Quanta.Entity.Entities.PassRightAccessibleFloorDetailEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsFront")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRear")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PassRightAccessibleFloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("PassRightAccessibleFloorId");

                    b.ToTable("PASS_RIGHT_ACCESSIBLE_FLOOR_DETAIL");
                });

            modelBuilder.Entity("KT.Quanta.Entity.Entities.PassRightAccessibleFloorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ElevatorGroupId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sign")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("PASS_RIGHT_ACCESSIBLE_FLOOR");
                });

            modelBuilder.Entity("KT.Quanta.Entity.Entities.PassRightDestinationFloorDetailEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsFront")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRear")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PassRightDestinationFloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("PassRightDestinationFloorId");

                    b.ToTable("PASS_RIGHT_DESTINATION_FLOOR_DETAIL");
                });

            modelBuilder.Entity("KT.Quanta.Entity.Entities.PassRightDestinationFloorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ElevatorGroupId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sign")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("PASS_RIGHT_DESTINATION_FLOOR_FLOOR");
                });

            modelBuilder.Entity("KT.Quanta.Entity.Kone.DopGlobalDefaultAccessFloorMaskEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("AccessMaskId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsDestinationFront")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDestinationRear")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSourceFront")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSourceRear")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AccessMaskId");

                    b.HasIndex("FloorId");

                    b.ToTable("DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK");
                });

            modelBuilder.Entity("KT.Quanta.Entity.Kone.DopGlobalDefaultAccessMaskEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("ConnectedState")
                        .HasColumnType("int");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ElevatorGroupId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ElevatorGroupId");

                    b.HasIndex("ConnectedState", "ElevatorGroupId")
                        .IsUnique();

                    b.ToTable("DOP_GLOBAL_DEFAULT_ACCESS_MASK");
                });

            modelBuilder.Entity("KT.Quanta.Entity.Kone.DopSpecificDefaultAccessFloorMaskEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("AccessMaskId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsDestinationFront")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDestinationRear")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("AccessMaskId", "FloorId")
                        .IsUnique();

                    b.ToTable("DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK");
                });

            modelBuilder.Entity("KT.Quanta.Entity.Kone.DopSpecificDefaultAccessMaskEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("ConnectedState")
                        .HasColumnType("int");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ElevatorGroupId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("HandleElevatorDeviceId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ElevatorGroupId");

                    b.HasIndex("HandleElevatorDeviceId");

                    b.HasIndex("ConnectedState", "ElevatorGroupId", "HandleElevatorDeviceId")
                        .IsUnique();

                    b.ToTable("DOP_SPECIFIC_DEFAULT_ACCESS_MASK");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.CardDeviceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("BrandModel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CardDeviceType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeviceType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("HandElevatorDeviceId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("HandleElevatorDeviceId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PortName")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProcessorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RelayDeviceId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("RelayDeviceOut")
                        .HasColumnType("int");

                    b.Property<string>("SerialConfigId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("HandElevatorDeviceId");

                    b.HasIndex("RelayDeviceId");

                    b.HasIndex("SerialConfigId");

                    b.HasIndex("ProcessorId", "PortName")
                        .IsUnique();

                    b.ToTable("CARD_DEVICE");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.CardDeviceRightGroupEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("CARD_DEVICE_RIGHT_GROUP");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.CardDeviceRightGroupRelationCardDeviceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("CardDeviceId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("CardDeviceRightGroupId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CardDeviceRightGroupId");

                    b.HasIndex("CardDeviceId", "CardDeviceRightGroupId")
                        .IsUnique();

                    b.ToTable("CARD_DEVICE_RIGHT_GROUP_RELATION_CARD_DEVICE");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.CommunicateInfoEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CommunicateInfos");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.DistributeErrorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DataContent")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DataId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DataModelName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeviceId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ErrorTimes")
                        .HasColumnType("int");

                    b.Property<string>("PartUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("DISTRIBUTE_ERROR");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.EdificeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("EDIFICE");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ElevatorGroupEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("BrandModel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EdificeId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Version")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("EdificeId");

                    b.ToTable("ELEVATOR_GROUP");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ElevatorGroupRelationFloorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ElevatorGroupId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("FloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("ElevatorGroupId", "FloorId")
                        .IsUnique();

                    b.ToTable("ELEVATOR_GROUP_RELATION_FLOOR");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ElevatorInfoEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ElevatorGroupId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RealId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ElevatorGroupId");

                    b.HasIndex("RealId", "ElevatorGroupId")
                        .IsUnique();

                    b.ToTable("ELEVATOR_INFO");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ElevatorServerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DBAccount")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DBPassword")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ElevatorGroupId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsMain")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PCAccount")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PCPassword")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElevatorGroupId");

                    b.ToTable("ELEVATOR_SERVER");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.FaceInfoEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FaceUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte[]>("Feature")
                        .HasColumnType("longblob");

                    b.Property<int>("FeatureSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("FACE_INFO");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.FloorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EdificeId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsFront")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRear")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RealFloorId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("EdificeId");

                    b.ToTable("FLOOR");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.HandleElevatorDeviceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("BrandModel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CommunicateType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeviceId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeviceType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ElevatorGroupId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("FaceActivateCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FaceAppId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FaceSdkKey")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("ProcessorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ElevatorGroupId");

                    b.HasIndex("FloorId");

                    b.HasIndex("ProcessorId");

                    b.ToTable("HANDLE_ELEVATOR_DEVICE");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.HandleElevatorInputDeviceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("AccessType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeviceType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("HandElevatorDeviceId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PortName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("HandElevatorDeviceId");

                    b.ToTable("HANDLE_ELEVATOR_INPUT_DEVICE");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.LoginUserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DBAddr")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DBName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DBPassword")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DBUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PCAddr")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PCPassword")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PCUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ServerAddress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("LOGIN_USER");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.PassRecordEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("AccessType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeviceId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeviceType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Extra")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte[]>("FaceImage")
                        .HasColumnType("longblob");

                    b.Property<long>("FaceImageSize")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsMask")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PassLocalTime")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PassRightId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PassRightSign")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("PassTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("WayType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("PASS_RECORD");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.PassRightEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("AccessType")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsFront")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRear")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PersonId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RightType")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Sign")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("TimeNow")
                        .HasColumnType("bigint");

                    b.Property<long>("TimeOut")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("PersonId");

                    b.HasIndex("Sign", "AccessType", "RightType")
                        .IsUnique();

                    b.ToTable("PASS_RIGHT");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.PassRightRelationCardDeviceRightGroupEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("CardDeviceRightGroupId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PassRightId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CardDeviceRightGroupId");

                    b.HasIndex("PassRightId", "CardDeviceRightGroupId")
                        .IsUnique();

                    b.ToTable("PASS_RIGHT_RELATION_CARD_DEVICE_RIGHT_GROUP");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.PassRightRelationFloorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsFront")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRear")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PassRightId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("PassRightId");

                    b.ToTable("PASS_RIGHT_RELATION_FLOOR");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.PersonEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("PERSON");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ProcessorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("BrandModel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeviceType")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("IpAddress", "Port", "DeviceType")
                        .IsUnique();

                    b.ToTable("PROCESSOR");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ProcessorFloorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FloorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProcessorId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("SortId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("ProcessorId", "FloorId")
                        .IsUnique();

                    b.HasIndex("ProcessorId", "SortId")
                        .IsUnique();

                    b.ToTable("PROCESSOR_FLOOR");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.RelayDeviceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("CommunicateType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress", "Port")
                        .IsUnique();

                    b.ToTable("RELAY_DEVICE");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.SerialConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("Baudrate")
                        .HasColumnType("int");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Databits")
                        .HasColumnType("int");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Encoding")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Parity")
                        .HasColumnType("int");

                    b.Property<int>("ReadTimeout")
                        .HasColumnType("int");

                    b.Property<int>("Stopbits")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SERIAL_CONFIG");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.SystemConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("EditedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Editor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Key")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SYSTEM_CONFIG");
                });

            modelBuilder.Entity("KT.Quanta.Entity.Entities.PassRightAccessibleFloorDetailEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.FloorEntity", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KT.Quanta.Entity.Entities.PassRightAccessibleFloorEntity", "PassRightAccessibleFloor")
                        .WithMany("PassRightAccessibleFloorDetails")
                        .HasForeignKey("PassRightAccessibleFloorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KT.Quanta.Entity.Entities.PassRightDestinationFloorDetailEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.FloorEntity", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KT.Quanta.Entity.Entities.PassRightDestinationFloorEntity", "PassRightDestinationFloor")
                        .WithMany("PassRightDestinationFloorDetails")
                        .HasForeignKey("PassRightDestinationFloorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KT.Quanta.Entity.Kone.DopGlobalDefaultAccessFloorMaskEntity", b =>
                {
                    b.HasOne("KT.Quanta.Entity.Kone.DopGlobalDefaultAccessMaskEntity", "AccessMask")
                        .WithMany("MaskFloors")
                        .HasForeignKey("AccessMaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KT.Quanta.Service.Entities.FloorEntity", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId");
                });

            modelBuilder.Entity("KT.Quanta.Entity.Kone.DopGlobalDefaultAccessMaskEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.ElevatorGroupEntity", "ElevatorGroup")
                        .WithMany()
                        .HasForeignKey("ElevatorGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KT.Quanta.Entity.Kone.DopSpecificDefaultAccessFloorMaskEntity", b =>
                {
                    b.HasOne("KT.Quanta.Entity.Kone.DopSpecificDefaultAccessMaskEntity", "AccessMask")
                        .WithMany("MaskFloors")
                        .HasForeignKey("AccessMaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KT.Quanta.Service.Entities.FloorEntity", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KT.Quanta.Entity.Kone.DopSpecificDefaultAccessMaskEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.ElevatorGroupEntity", "ElevatorGroup")
                        .WithMany()
                        .HasForeignKey("ElevatorGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KT.Quanta.Service.Entities.HandleElevatorDeviceEntity", "HandleElevatorDevice")
                        .WithMany()
                        .HasForeignKey("HandleElevatorDeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.CardDeviceEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.HandleElevatorDeviceEntity", "HandElevatorDevice")
                        .WithMany()
                        .HasForeignKey("HandElevatorDeviceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KT.Quanta.Service.Entities.ProcessorEntity", "Processor")
                        .WithMany("CardDevices")
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KT.Quanta.Service.Entities.RelayDeviceEntity", "RelayDevice")
                        .WithMany()
                        .HasForeignKey("RelayDeviceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KT.Quanta.Service.Entities.SerialConfigEntity", "SerialConfig")
                        .WithMany()
                        .HasForeignKey("SerialConfigId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.CardDeviceRightGroupRelationCardDeviceEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.CardDeviceEntity", "CardDevice")
                        .WithMany()
                        .HasForeignKey("CardDeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KT.Quanta.Service.Entities.CardDeviceRightGroupEntity", "CardDeviceRightGroup")
                        .WithMany("RelationCardDevices")
                        .HasForeignKey("CardDeviceRightGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ElevatorGroupEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.EdificeEntity", "Edifice")
                        .WithMany()
                        .HasForeignKey("EdificeId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ElevatorGroupRelationFloorEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.ElevatorGroupEntity", "ElevatorGroup")
                        .WithMany("RelationFloors")
                        .HasForeignKey("ElevatorGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KT.Quanta.Service.Entities.FloorEntity", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ElevatorInfoEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.ElevatorGroupEntity", "ElevatorGroup")
                        .WithMany("ElevatorInfos")
                        .HasForeignKey("ElevatorGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ElevatorServerEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.ElevatorGroupEntity", "ElevatorGroup")
                        .WithMany("ElevatorServers")
                        .HasForeignKey("ElevatorGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.FloorEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.EdificeEntity", "Edifice")
                        .WithMany("Floors")
                        .HasForeignKey("EdificeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.HandleElevatorDeviceEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.ElevatorGroupEntity", "ElevatorGroup")
                        .WithMany()
                        .HasForeignKey("ElevatorGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KT.Quanta.Service.Entities.FloorEntity", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KT.Quanta.Service.Entities.ProcessorEntity", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId");
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.HandleElevatorInputDeviceEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.HandleElevatorDeviceEntity", "HandElevatorDevice")
                        .WithMany()
                        .HasForeignKey("HandElevatorDeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.PassRightEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.FloorEntity", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KT.Quanta.Service.Entities.PersonEntity", "Person")
                        .WithMany("PassRights")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.PassRightRelationCardDeviceRightGroupEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.CardDeviceRightGroupEntity", "CardDeviceRightGroup")
                        .WithMany("RelationPassRights")
                        .HasForeignKey("CardDeviceRightGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KT.Quanta.Service.Entities.PassRightEntity", "PassRight")
                        .WithMany("RelationCardDeviceRightGroups")
                        .HasForeignKey("PassRightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.PassRightRelationFloorEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.FloorEntity", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KT.Quanta.Service.Entities.PassRightEntity", "PassRight")
                        .WithMany("RelationFloors")
                        .HasForeignKey("PassRightId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ProcessorEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.FloorEntity", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("KT.Quanta.Service.Entities.ProcessorFloorEntity", b =>
                {
                    b.HasOne("KT.Quanta.Service.Entities.FloorEntity", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KT.Quanta.Service.Entities.ProcessorEntity", "Processor")
                        .WithMany("ProcessorFloors")
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
