ALTER TABLE `Persons` ADD `CardNumber` longtext CHARACTER SET utf8mb4 NULL;

ALTER TABLE `ELEVATOR_INFO` MODIFY COLUMN `RealId` varchar(255) CHARACTER SET utf8mb4 NULL;

ALTER TABLE `ELEVATOR_INFO` ADD `ElevatorGroupId` varchar(255) CHARACTER SET utf8mb4 NULL;

CREATE INDEX `IX_ELEVATOR_INFO_ElevatorGroupId` ON `ELEVATOR_INFO` (`ElevatorGroupId`);

CREATE UNIQUE INDEX `IX_ELEVATOR_INFO_RealId_ElevatorGroupId` ON `ELEVATOR_INFO` (`RealId`, `ElevatorGroupId`);

ALTER TABLE `ELEVATOR_INFO` ADD CONSTRAINT `FK_ELEVATOR_INFO_ELEVATOR_GROUP_ElevatorGroupId` FOREIGN KEY (`ElevatorGroupId`) REFERENCES `ELEVATOR_GROUP` (`Id`) ON DELETE CASCADE;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20200717065954_V1.5.9', '3.1.2');
