DROP TABLE `PASS_RIGHT_DESTINATION_FLOOR_DETAIL`;

ALTER TABLE `PASS_RIGHT_DESTINATION_FLOOR_FLOOR` ADD `FloorId` varchar(255) CHARACTER SET utf8mb4 NULL;

ALTER TABLE `PASS_RIGHT_DESTINATION_FLOOR_FLOOR` ADD `IsFront` tinyint(1) NOT NULL DEFAULT FALSE;

ALTER TABLE `PASS_RIGHT_DESTINATION_FLOOR_FLOOR` ADD `IsRear` tinyint(1) NOT NULL DEFAULT FALSE;

CREATE INDEX `IX_PASS_RIGHT_DESTINATION_FLOOR_FLOOR_FloorId` ON `PASS_RIGHT_DESTINATION_FLOOR_FLOOR` (`FloorId`);

ALTER TABLE `PASS_RIGHT_DESTINATION_FLOOR_FLOOR` ADD CONSTRAINT `FK_PASS_RIGHT_DESTINATION_FLOOR_FLOOR_FLOOR_FloorId` FOREIGN KEY (`FloorId`) REFERENCES `FLOOR` (`Id`) ON DELETE CASCADE;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210330084227_v1.5.375', '3.1.7');

