ALTER TABLE `PASS_RIGHT_AUXILIARY_DETAIL` DROP FOREIGN KEY `FK_PASS_RIGHT_AUXILIARY_DETAIL_PASS_RIGHT_AUXILIARY_PassRightAu~`;

ALTER TABLE `PASS_RIGHT_AUXILIARY_DETAIL` DROP FOREIGN KEY `FK_PASS_RIGHT_AUXILIARY_DETAIL_PASS_RIGHT_AUXILIARY_PassRightA~1`;

ALTER TABLE `PASS_RIGHT_AUXILIARY_DETAIL` DROP INDEX `IX_PASS_RIGHT_AUXILIARY_DETAIL_PassRightAuxiliaryEntityId`;

ALTER TABLE `PASS_RIGHT_AUXILIARY_DETAIL` DROP COLUMN `PassRightAuxiliaryEntityId`;

ALTER TABLE `PASS_RIGHT_AUXILIARY_DETAIL` ADD CONSTRAINT `FK_PASS_RIGHT_AUXILIARY_DETAIL_PASS_RIGHT_AUXILIARY_PassRightAu~` FOREIGN KEY (`PassRightAuxiliaryId`) REFERENCES `PASS_RIGHT_AUXILIARY` (`Id`) ON DELETE CASCADE;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210323095943_v1.5.373', '3.1.7');

