ALTER TABLE `PASS_RIGHT_RELATION_FLOOR` DROP COLUMN `Direction`;

ALTER TABLE `PASS_RIGHT_AUXILIARY_DETAIL` DROP COLUMN `Direction`;

ALTER TABLE `PASS_RIGHT` DROP COLUMN `Direction`;

ALTER TABLE `HANDLE_ELEVATOR_DEVICE_AUXILIARY` DROP COLUMN `Direction`;

ALTER TABLE `FLOOR` DROP COLUMN `Direction`;

ALTER TABLE `PASS_RIGHT_RELATION_FLOOR` ADD `IsFront` tinyint(1) NOT NULL DEFAULT FALSE;

ALTER TABLE `PASS_RIGHT_RELATION_FLOOR` ADD `IsRear` tinyint(1) NOT NULL DEFAULT FALSE;

ALTER TABLE `PASS_RIGHT_AUXILIARY_DETAIL` ADD `IsFront` tinyint(1) NOT NULL DEFAULT FALSE;

ALTER TABLE `PASS_RIGHT_AUXILIARY_DETAIL` ADD `IsRear` tinyint(1) NOT NULL DEFAULT FALSE;

ALTER TABLE `PASS_RIGHT` ADD `IsFront` tinyint(1) NOT NULL DEFAULT FALSE;

ALTER TABLE `PASS_RIGHT` ADD `IsRear` tinyint(1) NOT NULL DEFAULT FALSE;

ALTER TABLE `HANDLE_ELEVATOR_DEVICE_AUXILIARY` ADD `IsFront` tinyint(1) NOT NULL DEFAULT FALSE;

ALTER TABLE `HANDLE_ELEVATOR_DEVICE_AUXILIARY` ADD `IsRear` tinyint(1) NOT NULL DEFAULT FALSE;

ALTER TABLE `FLOOR` ADD `IsFront` tinyint(1) NOT NULL DEFAULT FALSE;

ALTER TABLE `FLOOR` ADD `IsRear` tinyint(1) NOT NULL DEFAULT FALSE;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210323081130_v1.5.372', '3.1.7');

