DROP TABLE `PASS_RIGHT_AUXILIARY_DETAIL`;

DROP TABLE `PASS_RIGHT_AUXILIARY`;

CREATE TABLE `PASS_RIGHT_ACCESSIBLE_FLOOR` (
    `Id` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    `Creator` longtext CHARACTER SET utf8mb4 NULL,
    `Editor` longtext CHARACTER SET utf8mb4 NULL,
    `CreatedTime` bigint NOT NULL,
    `EditedTime` bigint NOT NULL,
    `Sign` longtext CHARACTER SET utf8mb4 NULL,
    `ElevatorGroupId` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_PASS_RIGHT_ACCESSIBLE_FLOOR` PRIMARY KEY (`Id`)
);

CREATE TABLE `PASS_RIGHT_DESTINATION_FLOOR_FLOOR` (
    `Id` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    `Creator` longtext CHARACTER SET utf8mb4 NULL,
    `Editor` longtext CHARACTER SET utf8mb4 NULL,
    `CreatedTime` bigint NOT NULL,
    `EditedTime` bigint NOT NULL,
    `Sign` longtext CHARACTER SET utf8mb4 NULL,
    `ElevatorGroupId` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_PASS_RIGHT_DESTINATION_FLOOR_FLOOR` PRIMARY KEY (`Id`)
);

CREATE TABLE `PASS_RIGHT_ACCESSIBLE_FLOOR_DETAIL` (
    `Id` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    `Creator` longtext CHARACTER SET utf8mb4 NULL,
    `Editor` longtext CHARACTER SET utf8mb4 NULL,
    `CreatedTime` bigint NOT NULL,
    `EditedTime` bigint NOT NULL,
    `FloorId` varchar(255) CHARACTER SET utf8mb4 NULL,
    `IsFront` tinyint(1) NOT NULL,
    `IsRear` tinyint(1) NOT NULL,
    `PassRightAccessibleFloorId` varchar(255) CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_PASS_RIGHT_ACCESSIBLE_FLOOR_DETAIL` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_PASS_RIGHT_ACCESSIBLE_FLOOR_DETAIL_FLOOR_FloorId` FOREIGN KEY (`FloorId`) REFERENCES `FLOOR` (`Id`) ON DELETE CASCADE,
    CONSTRAINT `FK_PASS_RIGHT_ACCESSIBLE_FLOOR_DETAIL_PASS_RIGHT_ACCESSIBLE_FLO~` FOREIGN KEY (`PassRightAccessibleFloorId`) REFERENCES `PASS_RIGHT_ACCESSIBLE_FLOOR` (`Id`) ON DELETE CASCADE
);

CREATE TABLE `PASS_RIGHT_DESTINATION_FLOOR_DETAIL` (
    `Id` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    `Creator` longtext CHARACTER SET utf8mb4 NULL,
    `Editor` longtext CHARACTER SET utf8mb4 NULL,
    `CreatedTime` bigint NOT NULL,
    `EditedTime` bigint NOT NULL,
    `FloorId` varchar(255) CHARACTER SET utf8mb4 NULL,
    `IsFront` tinyint(1) NOT NULL,
    `IsRear` tinyint(1) NOT NULL,
    `PassRightDestinationFloorId` varchar(255) CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_PASS_RIGHT_DESTINATION_FLOOR_DETAIL` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_PASS_RIGHT_DESTINATION_FLOOR_DETAIL_FLOOR_FloorId` FOREIGN KEY (`FloorId`) REFERENCES `FLOOR` (`Id`) ON DELETE CASCADE,
    CONSTRAINT `FK_PASS_RIGHT_DESTINATION_FLOOR_DETAIL_PASS_RIGHT_DESTINATION_F~` FOREIGN KEY (`PassRightDestinationFloorId`) REFERENCES `PASS_RIGHT_DESTINATION_FLOOR_FLOOR` (`Id`) ON DELETE CASCADE
);

CREATE INDEX `IX_PASS_RIGHT_ACCESSIBLE_FLOOR_DETAIL_FloorId` ON `PASS_RIGHT_ACCESSIBLE_FLOOR_DETAIL` (`FloorId`);

CREATE INDEX `IX_PASS_RIGHT_ACCESSIBLE_FLOOR_DETAIL_PassRightAccessibleFloorId` ON `PASS_RIGHT_ACCESSIBLE_FLOOR_DETAIL` (`PassRightAccessibleFloorId`);

CREATE INDEX `IX_PASS_RIGHT_DESTINATION_FLOOR_DETAIL_FloorId` ON `PASS_RIGHT_DESTINATION_FLOOR_DETAIL` (`FloorId`);

CREATE INDEX `IX_PASS_RIGHT_DESTINATION_FLOOR_DETAIL_PassRightDestinationFloo~` ON `PASS_RIGHT_DESTINATION_FLOOR_DETAIL` (`PassRightDestinationFloorId`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210330073521_v1.5.374', '3.1.7');

