ALTER TABLE `DOP_SPECIFIC_DEFAULT_ACCESS_MASK` MODIFY COLUMN `HandleElevatorDeviceId` varchar(255) CHARACTER SET utf8mb4 NULL;

CREATE INDEX `IX_DOP_SPECIFIC_DEFAULT_ACCESS_MASK_ElevatorGroupId` ON `DOP_SPECIFIC_DEFAULT_ACCESS_MASK` (`ElevatorGroupId`);

CREATE INDEX `IX_DOP_SPECIFIC_DEFAULT_ACCESS_MASK_HandleElevatorDeviceId` ON `DOP_SPECIFIC_DEFAULT_ACCESS_MASK` (`HandleElevatorDeviceId`);

CREATE INDEX `IX_DOP_GLOBAL_DEFAULT_ACCESS_MASK_ElevatorGroupId` ON `DOP_GLOBAL_DEFAULT_ACCESS_MASK` (`ElevatorGroupId`);

ALTER TABLE `DOP_GLOBAL_DEFAULT_ACCESS_MASK` ADD CONSTRAINT `FK_DOP_GLOBAL_DEFAULT_ACCESS_MASK_ELEVATOR_GROUP_ElevatorGroupId` FOREIGN KEY (`ElevatorGroupId`) REFERENCES `ELEVATOR_GROUP` (`Id`) ON DELETE CASCADE;

ALTER TABLE `DOP_SPECIFIC_DEFAULT_ACCESS_MASK` ADD CONSTRAINT `FK_DOP_SPECIFIC_DEFAULT_ACCESS_MASK_ELEVATOR_GROUP_ElevatorGrou~` FOREIGN KEY (`ElevatorGroupId`) REFERENCES `ELEVATOR_GROUP` (`Id`) ON DELETE CASCADE;

ALTER TABLE `DOP_SPECIFIC_DEFAULT_ACCESS_MASK` ADD CONSTRAINT `FK_DOP_SPECIFIC_DEFAULT_ACCESS_MASK_HANDLE_ELEVATOR_DEVICE_Hand~` FOREIGN KEY (`HandleElevatorDeviceId`) REFERENCES `HANDLE_ELEVATOR_DEVICE` (`Id`) ON DELETE CASCADE;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210315090319_v1.5.364', '3.1.7');
