DROP PROCEDURE IF EXISTS `POMELO_BEFORE_DROP_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255))
BEGIN
	DECLARE HAS_AUTO_INCREMENT_ID TINYINT(1);
	DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
	DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
	DECLARE SQL_EXP VARCHAR(1000);
	SELECT COUNT(*)
		INTO HAS_AUTO_INCREMENT_ID
		FROM `information_schema`.`COLUMNS`
		WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
			AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
			AND `Extra` = 'auto_increment'
			AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
	IF HAS_AUTO_INCREMENT_ID THEN
		SELECT `COLUMN_TYPE`
			INTO PRIMARY_KEY_TYPE
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
		SELECT `COLUMN_NAME`
			INTO PRIMARY_KEY_COLUMN_NAME
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
		SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL;');
		SET @SQL_EXP = SQL_EXP;
		PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
		EXECUTE SQL_EXP_EXECUTE;
		DEALLOCATE PREPARE SQL_EXP_EXECUTE;
	END IF;
END //
DELIMITER ;

DROP PROCEDURE IF EXISTS `POMELO_AFTER_ADD_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255), IN `COLUMN_NAME_ARGUMENT` VARCHAR(255))
BEGIN
	DECLARE HAS_AUTO_INCREMENT_ID INT(11);
	DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
	DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
	DECLARE SQL_EXP VARCHAR(1000);
	SELECT COUNT(*)
		INTO HAS_AUTO_INCREMENT_ID
		FROM `information_schema`.`COLUMNS`
		WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
			AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
			AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
			AND `COLUMN_TYPE` LIKE '%int%'
			AND `COLUMN_KEY` = 'PRI';
	IF HAS_AUTO_INCREMENT_ID THEN
		SELECT `COLUMN_TYPE`
			INTO PRIMARY_KEY_TYPE
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
				AND `COLUMN_TYPE` LIKE '%int%'
				AND `COLUMN_KEY` = 'PRI';
		SELECT `COLUMN_NAME`
			INTO PRIMARY_KEY_COLUMN_NAME
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
				AND `COLUMN_TYPE` LIKE '%int%'
				AND `COLUMN_KEY` = 'PRI';
		SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL AUTO_INCREMENT;');
		SET @SQL_EXP = SQL_EXP;
		PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
		EXECUTE SQL_EXP_EXECUTE;
		DEALLOCATE PREPARE SQL_EXP_EXECUTE;
	END IF;
END //
DELIMITER ;

ALTER TABLE `DopGlobalDefaultAccessFloorMasks` DROP FOREIGN KEY `FK_DopGlobalDefaultAccessFloorMasks_DopGlobalDefaultAccessMasks~`;

ALTER TABLE `DopSpecificDefaultAccessFloorMasks` DROP FOREIGN KEY `FK_DopSpecificDefaultAccessFloorMasks_DopSpecificDefaultAccessM~`;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'DopSpecificDefaultAccessMasks');
ALTER TABLE `DopSpecificDefaultAccessMasks` DROP PRIMARY KEY;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'DopSpecificDefaultAccessFloorMasks');
ALTER TABLE `DopSpecificDefaultAccessFloorMasks` DROP PRIMARY KEY;

ALTER TABLE `DopSpecificDefaultAccessFloorMasks` DROP INDEX `IX_DopSpecificDefaultAccessFloorMasks_AccessMaskId_Floor`;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'DopGlobalDefaultAccessMasks');
ALTER TABLE `DopGlobalDefaultAccessMasks` DROP PRIMARY KEY;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'DopGlobalDefaultAccessFloorMasks');
ALTER TABLE `DopGlobalDefaultAccessFloorMasks` DROP PRIMARY KEY;

ALTER TABLE `DopSpecificDefaultAccessFloorMasks` DROP COLUMN `Floor`;

ALTER TABLE `DopGlobalDefaultAccessFloorMasks` DROP COLUMN `Floor`;

ALTER TABLE `DopSpecificDefaultAccessMasks` RENAME `DOP_SPECIFIC_DEFAULT_ACCESS_MASK`;

ALTER TABLE `DopSpecificDefaultAccessFloorMasks` RENAME `DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK`;

ALTER TABLE `DopGlobalDefaultAccessMasks` RENAME `DOP_GLOBAL_DEFAULT_ACCESS_MASK`;

ALTER TABLE `DopGlobalDefaultAccessFloorMasks` RENAME `DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK`;

ALTER TABLE `DOP_SPECIFIC_DEFAULT_ACCESS_MASK` RENAME INDEX `IX_DopSpecificDefaultAccessMasks_ConnectedState_ElevatorGroupId~` TO `IX_DOP_SPECIFIC_DEFAULT_ACCESS_MASK_ConnectedState_ElevatorGrou~`;

ALTER TABLE `DOP_GLOBAL_DEFAULT_ACCESS_MASK` RENAME INDEX `IX_DopGlobalDefaultAccessMasks_ConnectedState_ElevatorGroupId` TO `IX_DOP_GLOBAL_DEFAULT_ACCESS_MASK_ConnectedState_ElevatorGroupId`;

ALTER TABLE `DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK` RENAME INDEX `IX_DopGlobalDefaultAccessFloorMasks_AccessMaskId` TO `IX_DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK_AccessMaskId`;

ALTER TABLE `DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK` ADD `FloorId` varchar(255) CHARACTER SET utf8mb4 NULL;

ALTER TABLE `DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK` ADD `FloorId` varchar(255) CHARACTER SET utf8mb4 NULL;

ALTER TABLE `DOP_SPECIFIC_DEFAULT_ACCESS_MASK` ADD CONSTRAINT `PK_DOP_SPECIFIC_DEFAULT_ACCESS_MASK` PRIMARY KEY (`Id`);
CALL POMELO_AFTER_ADD_PRIMARY_KEY(NULL, 'DOP_SPECIFIC_DEFAULT_ACCESS_MASK', 'Id');

ALTER TABLE `DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK` ADD CONSTRAINT `PK_DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK` PRIMARY KEY (`Id`);
CALL POMELO_AFTER_ADD_PRIMARY_KEY(NULL, 'DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK', 'Id');

ALTER TABLE `DOP_GLOBAL_DEFAULT_ACCESS_MASK` ADD CONSTRAINT `PK_DOP_GLOBAL_DEFAULT_ACCESS_MASK` PRIMARY KEY (`Id`);
CALL POMELO_AFTER_ADD_PRIMARY_KEY(NULL, 'DOP_GLOBAL_DEFAULT_ACCESS_MASK', 'Id');

ALTER TABLE `DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK` ADD CONSTRAINT `PK_DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK` PRIMARY KEY (`Id`);
CALL POMELO_AFTER_ADD_PRIMARY_KEY(NULL, 'DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK', 'Id');

CREATE INDEX `IX_DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK_FloorId` ON `DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK` (`FloorId`);

CREATE UNIQUE INDEX `IX_DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK_AccessMaskId_FloorId` ON `DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK` (`AccessMaskId`, `FloorId`);

CREATE INDEX `IX_DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK_FloorId` ON `DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK` (`FloorId`);

ALTER TABLE `DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK` ADD CONSTRAINT `FK_DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK_DOP_GLOBAL_DEFAULT_ACCE~` FOREIGN KEY (`AccessMaskId`) REFERENCES `DOP_GLOBAL_DEFAULT_ACCESS_MASK` (`Id`) ON DELETE CASCADE;

ALTER TABLE `DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK` ADD CONSTRAINT `FK_DOP_GLOBAL_DEFAULT_ACCESS_FLOOR_MASK_FLOOR_FloorId` FOREIGN KEY (`FloorId`) REFERENCES `FLOOR` (`Id`) ON DELETE RESTRICT;

ALTER TABLE `DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK` ADD CONSTRAINT `FK_DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK_DOP_SPECIFIC_DEFAULT_~` FOREIGN KEY (`AccessMaskId`) REFERENCES `DOP_SPECIFIC_DEFAULT_ACCESS_MASK` (`Id`) ON DELETE CASCADE;

ALTER TABLE `DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK` ADD CONSTRAINT `FK_DOP_SPECIFIC_DEFAULT_ACCESS_FLOOR_MASK_FLOOR_FloorId` FOREIGN KEY (`FloorId`) REFERENCES `FLOOR` (`Id`) ON DELETE CASCADE;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210315062335_v1.5.363', '3.1.7');

DROP PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`;

DROP PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`;
